dist: trusty

cache:
  directories:
    # Cache directory for older Composer versions.
    - $HOME/.composer/cache/files
    # Cache directory for more recent Composer versions.
    - $HOME/.cache/composer/files

language:
  - php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - "7.4snapshot"

matrix:
  fast_finish: true
  include:
    - php: 7.3
      env: PHPCS=1

allow_failures:
  # Allow failures for unstable builds.
  - php: "7.4snapshot"

before_install:
    - composer install

script:
  # Validate the composer.json file.
  # @link https://getcomposer.org/doc/03-cli.md#validate
  - composer validate --no-check-all --strict

  # Lint the PHP files against parse errors.
  - composer lint

  # Check the code against the standards as documented in the phpcs.xml.dist file.
  - if [[ "$PHPCS" == 1 ]]; then composer checkcs; fi
